#
# Module manifest for module 'SharePointQuotaManagement'
#
# Generated by: James Coe
#
# Generated on: 12/9/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SharePointQuotaManagement.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '125d75ee-9667-453e-ab00-1d73fad44871'

# Author of this module
Author = 'James Coe'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2016 James Coe. Released under the MIT License.'

# Description of the functionality provided by this module
Description = 'This module provides commandlets that help with management of quotas and quota templates in SharePoint 2013.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = 

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('LoadSharePointSnapin.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'SharePointQuotaManagement.Formats.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('SharePointQuotaManagement.psd1','LoadSharePointSnapin.ps1','SharePointQuotaManagement.psm1','SharePointQuotaManagement.Formats.ps1xml','about_SharePointQuotaManagement.help.txt','License.txt')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
